#%RAML 1.0 DataType
type: object
properties:
  name:
    type: string
    required: true
  description:
    type: string
    required: false
  duration:
    type: integer
  price:
    type: number
  enrollment_year:
    type: number
